### ISSUE TITLE
Allow set nginx worker_rlimit_nofile directive

### ISSUE THREAD

**Issue by acuervof** [idealista/nginx_role#32]
Role doesn't allow to set worker_rlimit_nofile directive

Because of that everytime is being used OS settings

**Comment by dortegau** [comment]
Hello @acuervof,

Why doesn't allow that directive? Raises an error?

**Comment by acuervof** [comment]
This directive is not present by default. In some cases it is necessary to set this directive in order to achieve the desired performance
