### ISSUE TITLE
Wrong configuration of proxy params

### ISSUE THREAD

**Issue by adrian-arapiles** [idealista/nginx_role#62]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filled: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aidealista
    * Checked that there is not already provided the described functionality

### Description

Reading documentation, the possible values of proxy_buffer_size can either 4k|8k depending of memory page of system. Now have 4m and it is redundant defined. 
```
proxy_buffers 8 4m;
proxy_buffer_size 4m;
```
Also role don't let override nginx.conf template:
### Steps to Reproduce

Always

**Expected behavior:** Nginx.conf can be override

**Actual behavior:**  Nginx.conf defined only in the role

**Reproduces how often:** 100%

### Versions

All versions.

**Comment by dortegau** [comment]
merged!
