### ISSUE TITLE
Parametrize PrivateTmp variable

### ISSUE THREAD

**Issue by gabyalises** [idealista/nginx_role#78]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filled: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aidealista
    * Checked that there is not already provided the described functionality

### Description
Parametrizing PrivateTmp variable to solve Debian 10 compatibilies

**Comment by dortegau** [comment]
merged 👍
